pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Python Tests / build (3.8) (pull_request)
      - base=master
    actions:
      merge:
        method: squash
        strict: true

  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=Python Tests / build (3.8) (pull_request)
    actions:
      merge:
        method: squash
        strict: true

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
