pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}