pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=build (3.10)
      - base=master
    actions:
      merge:
        method: squash

  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - status-success=build (3.10)
    actions:
      merge:
        method: squash

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
